# 21 In-Class Assignment: Solve Linear Systems of Equations

In order to get the most out of this assignment, you are strongly encouraged to try to complete this assignment on your own before class and bring any questions you have for class. This assignment is not for credit, but it reviewes some important topics mainly from the first class of the semester.

### Goals for today's assignment 


1. [Linear Systems](#Linear-Systems)
2. [Under Defined Systems](#Under-Defined-Systems)
3. [Invertible Matrices](#Invertible-Systems)
4. [Overdefined systems](#Overdefined-systems)
5. [Applications](#Applications)
6. [Column Picture and Span](#Col-pic)
7. [Transformations](#Transformations)





---
<a name=Linear-Systems></a>
## 1. Linear Systems





In this course, we learned how to represent linear systems which basically consists of equations added sums of multiple numbers in the form:

$$b = a_1x_1+a_2x_2+a_3x_3 + \ldots a_mx_m$$

Systems of linear equations are multiple equations of the above form with basically the same unknowns but different values of $a$ and $b$. 

$$b_1 = a_{11}x_1+a_{12}x_2+a_{13}x_3 + \ldots a_{1n}x_n$$
$$b_2 = a_{21}x_1+a_{22}x_2+a_{23}x_3 + \ldots a_{2n}x_n$$
$$b_3 = a_{31}x_1+a_{32}x_2+a_{33}x_3 + \ldots a_{3n}x_n$$
$$\vdots$$
$$b_m = a_{m1}x_1+a_{m2}x_2+a_{m3}x_3 + \ldots a_{mn}x_n$$

The above equations can be represented in matrix form as follows:

$$ 
\left[ 
\begin{matrix}
    b_1 \\ 
    b_2 \\
    b_3 \\
    \vdots \\
    b_m
 \end{matrix}
\right] 
=
\left[ 
\begin{matrix}
 a_{11} & a_{12} & a_{13} &   & a_{1n} \\ 
 a_{21} & a_{22} & a_{23} &  \ldots & a_{2n} \\ 
  a_{31} & a_{32} & a_{33} &   & a_{3n} \\ 
  & \vdots &   & \ddots & \vdots \\ 
 a_{m1} & a_{m2} & a_{m3} &   & a_{mn} 
\end{matrix}
\right] 
\left[ 
\begin{matrix}
    x_1 \\ 
    x_2 \\
    x_3 \\
    \vdots \\
    x_n
\end{matrix}
\right] 
$$

Which can also be represented in "augmented" form as follows:

$$ 
\left[ 
\begin{matrix}
 a_{11} & a_{12} & a_{13} &   & a_{1n} \\ 
 a_{21} & a_{22} & a_{23} &  \ldots & a_{2n} \\ 
  a_{31} & a_{32} & a_{33} &   & a_{3n} \\ 
  & \vdots &   & \ddots & \vdots \\ 
 a_{m1} & a_{m2} & a_{m3} &   & a_{mn} 
\end{matrix}
 \, \middle\vert \,
\begin{matrix}
    b_1 \\ 
    b_2 \\
    b_3 \\
    \vdots \\
    b_m
\end{matrix}
\right] 
$$

The above systems can be modified into equivelent systems using combinations of the following operators. 

1. Multiply any row of a matrix by a constant
2. Add the contents of one row by another row.
3. Swap any two rows. 

Often the 1st and 2nd operator can be combined where a row is multipled by a constanet and then added (or subtracted) from another row. 

&#9989; **<font color=red>QUESTION:</font>**  Consider the matrix $A= \left[ 
\begin{matrix} 1 & 3 \\ 0 & 2 \end{matrix}\right]$. What elementary operations can you use to put the above matrix into its reduced row echelon form? 

Put your answer to the above question here.

###Answer

 We need to divide the second row by 2, then add (-3) times the second row to the first row. This will convert the matrix A to the identity matrix, which is in RREF.

###Answer

---
<a name=Under-Defined-Systems></a>
## 2. Under Defined Systems




An under-defined system is one that is non-invertible. These systems may have an infinite number of possible solutions and solving them involves finding a set of simplified equations that represent all solutions; or they may have NO solutions, depending on the right hand side. 

Often the simplest way to solve an under-defined systems of equations is to extract the solution directly from the reduced row echelon form.  

Generally, if there is an infinite number of solutions, there will be free variable(s), in terms of which we will be able to express the rest of the non-free variables (variables that have pivots in the corresponding columns).

&#9989; **<font color=red>QUESTION:</font>**  What is the reduced row echelon form of the matrix $A= \left[ 
\begin{matrix} 1 & 3 \\ 2 & 6 \end{matrix}\right]$.

In [1]:
#put your answer to the above quesiton here.

In [2]:
import sympy as sym
A=sym.Matrix([[1,3],[2,6]])
A.rref()

(Matrix([
 [1, 3],
 [0, 0]]),
 (0,))

&#9989; **<font color=red>QUESTION:</font>**  What are the solutions to the above systems of equations if $b= \left[ 
\begin{matrix} 10\\ 3 \end{matrix}\right]$?

In [3]:
#put your answer to the above quesiton here.

In [4]:
##ANSWER##
import numpy as np
import sympy as sym
Ag = np.matrix([[1, 3, 10], [2, 6, 3]])
sym.Matrix(Ag).rref()[0]


#Note to instructors.  There is no solutions to this problem.
##ANSWER##

Matrix([
[1, 3, 0],
[0, 0, 1]])

&#9989; **<font color=red>QUESTION:</font>**  What are the solutions to the above systems of equations if $b= \left[ 
\begin{matrix} 6\\ 12 \end{matrix}\right]$?

In [5]:
#put your answer to the above quesiton here.

In [6]:
##ANSWER##
Ag2 = np.matrix([[1, 3, 6], [2, 6, 12]])
sym.Matrix(Ag2).rref()[0]


#Note to instructors.  There is no solutions to this problem.
##ANSWER##

Matrix([
[1, 3, 6],
[0, 0, 0]])

$x_2$ is a free variable and $x_1=6-3x_2$. Thus, there are an infinite number of solutions to the system, and they are of the form $x= \left[ 
\begin{matrix} 6-3x_2\\ x_2 \end{matrix}\right]$


---
<a name=Invertible-Systems></a>
## 3. Invertible Matrices

An invertible matrix is a square matrix, $A$, which satisfies the following properties:

1. $|A|\ne 0$
1. There exists an inverse matrix $A^{-1}$ such that $ A^{-1}A = AA^{-1} = I $
1. $(A^{-1})^{-1} = A$
2. $(cA)^{-1} = \frac{1}{c}A^{-1}$
3. $(AB)^{-1} = B^{-1}A^{-1}$
4. $(A^n)^{-1} = (A^{-1})^n$
1. $(A^\top)^{-1} = (A^{-1})^\top$  here $A^\top$ is the transpose of the matrix $A$.

Consider the following system of equations:

$$\begin{bmatrix}5&-2&2 \\ 4 & -3 &4 \\ 4& -6 &7 \end{bmatrix}\begin{bmatrix}x_1\\x_2\\x_3\end{bmatrix}=\begin{bmatrix}1\\2\\3\end{bmatrix}$$



In [7]:
import numpy as np
import sympy as sym

In [8]:
A = np.matrix([[5, -2, 2], [4, -3, 4], [4,-6,7]])
b = np.matrix([[1],[2],[3]])
display(sym.Matrix(A))
display(sym.Matrix(b))

Matrix([
[5, -2, 2],
[4, -3, 4],
[4, -6, 7]])

Matrix([
[1],
[2],
[3]])

**Iterative algorithms (e.g. Jacobi method):** 
+ May require many iterations
+ They do not work for all square invertible systems. 

**Non-iterative algorithms:** 
+ Gauss elimination (rref)
+ Find the inverse of the matrix $A$ and $x= A^{-1}b$

&#9989; **<font color=red>DO THIS:</font>** Pick at least two methods to solve the system of equations and compare them. 

In [9]:
#put your answer here

In [10]:
##ANSWER##

A_aug = sym.Matrix(np.append(A,b, axis=1))


x = A_aug.rref()[0][:,3]
print(A*np.matrix(x)-b)
A*np.matrix(x)==b
##ANSWER## 



[[0]
 [0]
 [0]]


matrix([[ True],
        [ True],
        [ True]])

##ANSWER##


Jacobi does not work here

For Jacobi we have that 

$$x_1^{n+1} = A_{11}^{-1}(b_1 - 0* x_1^n -A_{12}x_2^n - A_{13}x_3^n )$$
$$x_2^{n+1} = A_{22}^{-1}(b_2 - A_{21}x_1^n - 0*x_2^n- A_{23}x_3^n )$$
$$x_3^{n+1} = A_{33}^{-1}(b_3 - A_{31}x_1^n - A_{32}x_2^n -0*x_3^n)$$

$$x^{n+1}=(Ad)^{-1} (b-Ao *x^n)$$

##ANSWER##

In [11]:
##ANSWER##
def jacobi(A, b):
    Ad = np.diag(np.diag(A))
    Ao = A - Ad
    x  = np.matrix(np.zeros((A.shape[0],1)))
    for i in range(100):
        x = np.linalg.inv(Ad)*(b - Ao*x) 
    return x
x = jacobi(A,b)
print(x)

[[-9.88250598e+17]
 [ 2.22717791e+18]
 [-1.59781826e+18]]


In [12]:
##ANSWER##
x = np.linalg.solve(A,b)
print(A*np.matrix(x)-b)
##ANSWER## 

[[0.]
 [0.]
 [0.]]


In [13]:
##ANSWER##
x = np.linalg.lstsq(A,b)[0]
print(A*np.matrix(x)-b)
##ANSWER## 

[[-5.55111512e-16]
 [-1.33226763e-15]
 [-4.44089210e-16]]


<ipython-input-13-8459a081d6f6>:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x = np.linalg.lstsq(A,b)[0]



---
<a name=Overdefined-systems></a>
## 4. Overdefined systems



We also learned solutions to overdefined systems (more equations than unknowns) often do not exist. However, we can estimate a solution using Least Squares fit.  

Consider the following system of equations:

$$\begin{bmatrix}5&-2&2 \\ 4 & -3 &4 \\ 4& -6 &7 \\ 6 & 3 & -3\end{bmatrix}\begin{bmatrix}x_1\\x_2\\x_3\end{bmatrix}=\begin{bmatrix}1\\2\\3\\-1\end{bmatrix}$$

&#9989; **<font color=red>Question:</font>** Does this system have an exact solution? Justify your answer.

In [14]:
#Put your answer to the above question here.

In [15]:
###Answer

M=sym.Matrix([[5,-2,2,1],[4,-3,4,2],[4,-6,7,3],[6,3,-3,-1]])
M.rref()
###Answer

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 0],
 [0, 0, 0, 1]]),
 (0, 1, 2, 3))

###Answer

The system has no solution - the fourth equation is equivalent to $0=1$.

###Answer

&#9989; **<font color=red>DO THIS:</font>** Solve the above using LSF. 

In [16]:
#Put your answer to the above question here.

In [17]:
###Answer
A=sym.Matrix([[5,-2,2],[4,-3,4],[4,-6,7],[6,3,-3]])
b=sym.Matrix([[1],[2],[3],[-1]])
x_hat=((A.T*A).inv())*A.T*b #### THIS IS THE LSF SOLUTION


p=A*x_hat # projection onto the column space of A
(A.T)*(b-p) # checking that the error is orthogonal to column space
###Answer

Matrix([
[0],
[0],
[0]])


---
<a name=Applications></a>
## 5. Applications 

A hospital dietician is planing a special diet for a certain patient. The total amount per meal of food groups A, B, and C must equal 400 grams. The amount of group A included in the diet is one-third that of group B, and the sum of the amounts of group A and group C should equal twice the amount of group B. 

&#9989; **<font color=red>DO THIS:</font>** Write a system of equations that describes the above situation.

###Answer

A+B+C=400

A=B/3

A+C=2B


###Answer


&#9989; **<font color=red>Question:</font>** How many grams of each food group should be included?

In [18]:
###answer

import numpy as np
A=np.matrix([[1,1,1],[1,-1/3,0],[1,-2,1]])
b=np.matrix([[400],[0],[0]])
x = np.linalg.solve(A,b)
x
###answer

matrix([[ 44.44444444],
        [133.33333333],
        [222.22222222]])

&#9989; **<font color=red>Question:</font>** Suppose we drop the requirement that the diet include one-third as much of group A as of group B. Describe the set of all possible solutions.

In [19]:
###answer

import sympy as sym
Ag=sym.Matrix([[1,1,1,400],[1,-2,1,0]])
sym.Matrix(Ag).rref()[0]

# B= 400/3, C-free variable, between 0 and 800/3, A=800/3-C
###answer

Matrix([
[1, 0, 1, 800/3],
[0, 1, 0, 400/3]])

&#9989; **<font color=red>Question:</font>** Suppose that, in addition to the conditions given in the original problem, foods A and B cost 2 cents per gram and food C costs 3 cents per gram, and that a meal must cost $8. Is a solution possible? Explain.

In [20]:
###answer


Ag2=np.matrix([[1,1,1,400],[1,-1/3,0,0],[1,-2,1,0],[2,2,3,800]])
sym.Matrix(Ag2).rref()[0]

# no - solution - the fourth equation in the RREF form is equivalent to 0=1
###answer

Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]])


---
<a name=Col-pic></a>
## 6. Column Picture and Span


Let $\mathbf u$, $\mathbf v$,  $\mathbf w$, $\mathbf x$, and $\mathbf y$ be vectors in $\mathbb R^3$, given by
	$
	\mathbf u = \left[ 
	\begin{array}{rr}
		1 \\
		-1 \\
		0
	\end{array}
	\right]
	$,
	$
	\mathbf v = \left[ 
	\begin{array}{rr}
		0 \\
		1 \\
		-1
	\end{array}
	\right]
	$, $
	\mathbf w = \left[ 
	\begin{array}{rr}
		2 \\
		-1 \\
		-1
	\end{array}
	\right]
	$, 
    $
	\mathbf x = \left[ 
	\begin{array}{rr}
		0 \\
		0 \\
		1
	\end{array}
	\right]
	$, and
	$
	\mathbf y = \left[ 
	\begin{array}{rr}
		1 \\
		4 \\
		-5
	\end{array}
	\right]
	$.

&#9989; **<font color=red>Question (6a):</font>** Find a basis for $\mbox{span}(\mathbf{u}, \mathbf{v}, \mathbf{w})$. Does $\mbox{span}(\mathbf{u}, \mathbf{v}, \mathbf{w})$ represent a line, a plane, or all of $\mathbb R^3$?

In [21]:
###answer

import sympy as sym
uvw=sym.Matrix([[1,-1,0],[0,1,-1],[2,-1,-1]])
sym.Matrix(uvw).rref()[0]

#Many possible answers - {u,v} is a basis, w=2u+v; [1,0,-1] and v=[0,1-1] also form a basis. span(u,v,w) forms a plane
###answer

Matrix([
[1, 0, -1],
[0, 1, -1],
[0, 0,  0]])

&#9989; **<font color=red>Question (6b):</font>** Find all solutions $(a,b,c)$ of $a\mathbf{u}+ b\mathbf{v}+c \mathbf{w}=\mathbf{x}$. In other words, find all possible ways $\mathbf x$ can be expressed as a linear combination of $\mathbf{u}, \mathbf{v}$, and $\mathbf{w}$.

In [22]:
###answer

Augx=sym.Matrix([[1,0,2,0],[-1,1,-1,0],[0,-1,-1,1]])
sym.Matrix(Augx).rref()[0]

#No solutions - the last equation is equivalent to 0=1
###answer

Matrix([
[1, 0, 2, 0],
[0, 1, 1, 0],
[0, 0, 0, 1]])

&#9989; **<font color=red>Question (6c):</font>** Find all solutions $(a,b,c)$ of $a\mathbf{u}+ b\mathbf{v}+c \mathbf{w}=\mathbf{y}$. In other words, find all possible ways $\mathbf y$ can be expressed as a linear combination of $\mathbf{u}, \mathbf{v}$, and $\mathbf{w}$.



In [23]:
###answer

Augy=sym.Matrix([[1,0,2,1],[-1,1,-1,4],[0,-1,-1,-5]])
sym.Matrix(Augy).rref()[0]

#Infinitely many solutions - x3 is a free variable, x1=1-2x3, x2=5-x3
###answer

Matrix([
[1, 0, 2, 1],
[0, 1, 1, 5],
[0, 0, 0, 0]])


---
<a name=Transformations></a>
## 7. Transformations

&#9989; **<font color=red>Question (7a):</font>** Construct a matrix $R$, which represents rotation in $\mathbb R^3$ around the y-axis by 45 degrees, in the counter-clockwise direction. 

In [24]:
###answer
import numpy as np
th=(np.pi/180)*45
R=np.matrix([[np.cos(th),0,-np.sin(th)],[0,1,0],[np.sin(th),0,np.cos(th)]])
R
###answer

matrix([[ 0.70710678,  0.        , -0.70710678],
        [ 0.        ,  1.        ,  0.        ],
        [ 0.70710678,  0.        ,  0.70710678]])

&#9989; **<font color=red>Question (7b):</font>** Construct a matrix $T$, which represents translation in $\mathbb R^3$ by vector $v=[2,3,-1]^T$. If the translation is in $\mathbb R^3$, what is the size of the matrix $T$?

In [25]:
###answer

T=np.matrix([[1,0,0,2],[0,1,0,3],[0,0,1,-1],[0,0,0,1]])
T
###answer

matrix([[ 1,  0,  0,  2],
        [ 0,  1,  0,  3],
        [ 0,  0,  1, -1],
        [ 0,  0,  0,  1]])

&#9989; **<font color=red>Question (7c):</font>** Now modify the matrix $R$, so that it can be multiplied by the matrix $T$. (Note, most likely you had $R$ be a $3\times 3 $ matrix and $T$ be a $4\times 4$ matrix).

In [26]:
###answer

R2=np.matrix([[np.cos(th),0,-np.sin(th),0],[0,1,0,0],[np.sin(th),0,np.cos(th),0],[0,0,0,1]])
R2
###answer
###answer

matrix([[ 0.70710678,  0.        , -0.70710678,  0.        ],
        [ 0.        ,  1.        ,  0.        ,  0.        ],
        [ 0.70710678,  0.        ,  0.70710678,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]])

&#9989; **<font color=red>Question (7d):</font>** Construct a matrix $M$, which represents rotation in $\mathbb R^3$ around the y-axis by 45 degrees, followed by translation by $v=[2,3,-1]^T$.

In [27]:
###answer

M=T*R2
M
###answer

matrix([[ 0.70710678,  0.        , -0.70710678,  2.        ],
        [ 0.        ,  1.        ,  0.        ,  3.        ],
        [ 0.70710678,  0.        ,  0.70710678, -1.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]])

&#9989; **<font color=red>Question (7e):</font>** What is the inverse of $M$? What does it represent physically? How is it related to the matrices $R$ and $T$?

In [28]:
###answer

Minv=np.linalg.inv(M)
np.linalg.inv(R2)*np.linalg.inv(T)-Minv #### M^{-1}=R2^{-1}*T^{-1}
###answer

matrix([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         -1.11022302e-16],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00]])

----

Written in part by Dr. Dirk Colbry, Michigan State University
<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.

---------
### Congratulations, we're done!

----